from typing import Tuple
from pandas import DataFrame
from numpy import ndarray

def downloadHousingData() -> None:
    """
    Downloads the Housing data zip file from a GitHub repository, create the 'data' directory if not exists and finally extracts the content from the zip file.

    Parameters
    None

    Returns
    None
    """
    ...

def saveGraph(graph_id: str, tight_layout: bool, graph_extension: str, resolution: int) -> None:
    """
    Downloads a graph generated by matplotlib with the specified name, graph extension and resolution.

    Parameters
    - graph_id (str): Graph name
    - tight_layout (bool): Activate the tigh_layout configuration
    - graph_extension (str): Extension to save the image (png, jpg, svg, etc...)
    - Resolution (int): DPI resolution for saving the figure

    Returns
    None
    """
    ...

def randomDataSplitter(data: DataFrame, test_ratio: float) -> Tuple[DataFrame, DataFrame]:
    """
    Splits a dataframe randomly into a test and train set for ML models.

    Parameters
    - data (DataFrame): A pandas DataFrame containing the data.
    - test_ratio (float): A ratio between 0 and 1 for the test set size proportion.

    Returns
    - trainSet (DataFrame): A pandas DataFrame with the train data.
    - testSet (DataFrame): A pandas DataFrame with the test data.
    """
    ...

def designedBarGraph(filename: str, labels: ndarray, values: ndarray, tittle: str, color: str) -> None:
    """
    This function creates a minimalistic and visually appealing bar graph and stores it as a png file in an image directory.

    Parameters
    - filename (str): The file name for the .png graph
    - labels (ndarray): The X-axis labels
    - values (ndarray): The Y-axis values
    - tittle (str): The graph tittle
    - color (str): The bars colors

    Returns
    None
    """